name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
    inputs:
      ov_commit_hash:
        description: 'OV commit Git Hash'
        required: true
      vpux_commit_hash:
        description: 'VPUX commit Git Hash'
        required: true
jobs:
  #################################################
  #   Job 1: Check and setup env. fm6pwlghr001
  #################################################
  set-prebuild-vars:
    runs-on: windows-latest
    outputs:
      ov_commit_hash: ${{  github.event.inputs.ov_commit_hash }}
      vpux_commit_hash: ${{  github.event.inputs.vpux_commit_hash }}
      prebuild_root_url: https://gfx-assets.intel.com/artifactory
      prebuild_asset_path: gfx-npu-assets
      prebuild_asset_name: vpux-prebuild
      prebuild_asset_version: ${{ steps.set-prebuild-package-name.outputs.prebuild_package_version }}
    steps:
      - name: Set prebuild package name
        id: set-prebuild-package-name
        run: |
          OV_GIT_COMMIT_HASH_FULL=${{ github.event.inputs.ov_commit_hash }}
          OV_GIT_COMMIT_HASH_SHORT=${OV_GIT_COMMIT_HASH_FULL:0:10}
          VPUX_GIT_COMMIT_HASH_FULL=${{ github.event.inputs.vpux_commit_hash }}
          VPUX_GIT_COMMIT_HASH_SHORT=${VPUX_GIT_COMMIT_HASH_FULL:0:10}  
          PREBUILD_PACKAGE_NAME="workflow-openvino-$OV_GIT_COMMIT_HASH_SHORT-vpux-$VPUX_GIT_COMMIT_HASH_SHORT"
          echo "Set Prebuild Package_name $PREBUILD_PACKAGE_NAME"
          echo "::set-output name=prebuild_package_version::$PREBUILD_PACKAGE_NAME"
        shell: bash
